spring:
  application:
    name: general-election-prod
  datasource:
    url: jdbc:postgresql://aaaicu.iptime.org:33068/general_election_member
    username: postgres # 데이터베이스 접속 계정
    password: ${DB_PASSWORD} # 데이터베이스 접속 비밀번호
    driver-class-name: org.postgresql.Driver # JDBC 드라이버 클래스 이름

  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션을 실행할 때마다 테이블을 자동으로 생성
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL의 Hibernate Dialect
        format_sql: true
        show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug # Hibernate가 실행하는 SQL 쿼리 디버깅을 위한 로그 레벨

general-election-server-host: https://api.yummy-things.xyz