spring:
  application:
    name: general-election-local
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug

general_election_hosts:
  community: http://localhost:18880

auth-info:
  kakao:
    redirect_uri: http:localhost:${server.port}/api/auth/kakao/callback

general-election-server-host: http://localhost:18890